<?xml version="1.0"?>
<!DOCTYPE feature_vector_file [
   <!ELEMENT feature_vector_file (comments, data_set+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT data_set (data_set_id, section*, feature*)>
   <!ELEMENT data_set_id (#PCDATA)>
   <!ELEMENT section (feature+)>
   <!ATTLIST section start CDATA ""
                     stop CDATA "">
   <!ELEMENT feature (name, v+)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT v (#PCDATA)>
]>

<feature_vector_file>

   <comments></comments>

	<data_set>
		<data_set_id>C:\Users\user\Desktop\New folder\Rock\wav\Aqualung - Jethro Tull.wav</data_set_id>
		<feature>
			<name>Magnitude Spectrum Overall Standard Deviation</name>
			<v>3.282E-3</v>
			<v>5.917E-3</v>
			<v>1.284E-2</v>
			<v>1.604E-2</v>
			<v>1.764E-2</v>
			<v>1.529E-2</v>
			<v>1.395E-2</v>
			<v>1.176E-2</v>
			<v>8.263E-3</v>
			<v>6.736E-3</v>
			<v>4.744E-3</v>
			<v>4.071E-3</v>
			<v>4.289E-3</v>
			<v>5.52E-3</v>
			<v>5.245E-3</v>
			<v>4.981E-3</v>
			<v>4.301E-3</v>
			<v>4.997E-3</v>
			<v>4.357E-3</v>
			<v>4.889E-3</v>
			<v>4.687E-3</v>
			<v>3.871E-3</v>
			<v>5.702E-3</v>
			<v>4.584E-3</v>
			<v>4.122E-3</v>
			<v>6.45E-3</v>
			<v>4.516E-3</v>
			<v>3.667E-3</v>
			<v>4.114E-3</v>
			<v>4.334E-3</v>
			<v>4.89E-3</v>
			<v>3.498E-3</v>
			<v>3.022E-3</v>
			<v>4.285E-3</v>
			<v>4.221E-3</v>
			<v>3.171E-3</v>
			<v>3.381E-3</v>
			<v>3.694E-3</v>
			<v>3.08E-3</v>
			<v>3.345E-3</v>
			<v>4.258E-3</v>
			<v>5.015E-3</v>
			<v>5.215E-3</v>
			<v>4.573E-3</v>
			<v>4.887E-3</v>
			<v>4.819E-3</v>
			<v>4.016E-3</v>
			<v>3.27E-3</v>
			<v>2.88E-3</v>
			<v>3.789E-3</v>
			<v>4.629E-3</v>
			<v>3.418E-3</v>
			<v>2.536E-3</v>
			<v>2.655E-3</v>
			<v>2.474E-3</v>
			<v>2.906E-3</v>
			<v>3.84E-3</v>
			<v>3.418E-3</v>
			<v>3.563E-3</v>
			<v>3.855E-3</v>
			<v>3.485E-3</v>
			<v>2.737E-3</v>
			<v>2.817E-3</v>
			<v>3.443E-3</v>
			<v>3.055E-3</v>
			<v>2.78E-3</v>
			<v>3.012E-3</v>
			<v>3.795E-3</v>
			<v>3.928E-3</v>
			<v>3.024E-3</v>
			<v>2.816E-3</v>
			<v>2.506E-3</v>
			<v>2.515E-3</v>
			<v>2.709E-3</v>
			<v>2.759E-3</v>
			<v>3.205E-3</v>
			<v>3.363E-3</v>
			<v>2.803E-3</v>
			<v>2.898E-3</v>
			<v>2.896E-3</v>
			<v>2.752E-3</v>
			<v>2.643E-3</v>
			<v>2.787E-3</v>
			<v>2.997E-3</v>
			<v>3.019E-3</v>
			<v>2.6E-3</v>
			<v>2.238E-3</v>
			<v>2.386E-3</v>
			<v>2.683E-3</v>
			<v>2.672E-3</v>
			<v>2.632E-3</v>
			<v>2.171E-3</v>
			<v>1.991E-3</v>
			<v>1.631E-3</v>
			<v>1.559E-3</v>
			<v>1.509E-3</v>
			<v>1.362E-3</v>
			<v>1.312E-3</v>
			<v>1.406E-3</v>
			<v>1.459E-3</v>
			<v>1.378E-3</v>
			<v>1.511E-3</v>
			<v>1.394E-3</v>
			<v>1.298E-3</v>
			<v>1.146E-3</v>
			<v>1.108E-3</v>
			<v>1.205E-3</v>
			<v>1.283E-3</v>
			<v>1.301E-3</v>
			<v>1.408E-3</v>
			<v>1.443E-3</v>
			<v>1.446E-3</v>
			<v>1.661E-3</v>
			<v>1.67E-3</v>
			<v>1.445E-3</v>
			<v>1.487E-3</v>
			<v>1.559E-3</v>
			<v>1.608E-3</v>
			<v>1.602E-3</v>
			<v>1.58E-3</v>
			<v>1.582E-3</v>
			<v>1.536E-3</v>
			<v>1.454E-3</v>
			<v>1.383E-3</v>
			<v>1.328E-3</v>
			<v>1.391E-3</v>
			<v>1.636E-3</v>
			<v>1.634E-3</v>
			<v>1.532E-3</v>
			<v>1.355E-3</v>
			<v>1.269E-3</v>
			<v>1.352E-3</v>
			<v>1.406E-3</v>
			<v>1.285E-3</v>
			<v>1.347E-3</v>
			<v>1.379E-3</v>
			<v>1.12E-3</v>
			<v>1.134E-3</v>
			<v>1.278E-3</v>
			<v>1.225E-3</v>
			<v>1.162E-3</v>
			<v>1.275E-3</v>
			<v>1.296E-3</v>
			<v>1.307E-3</v>
			<v>1.113E-3</v>
			<v>1.041E-3</v>
			<v>9.921E-4</v>
			<v>8.259E-4</v>
			<v>8.359E-4</v>
			<v>9.07E-4</v>
			<v>9.989E-4</v>
			<v>1.124E-3</v>
			<v>9.145E-4</v>
			<v>7.747E-4</v>
			<v>7.788E-4</v>
			<v>8.285E-4</v>
			<v>8.703E-4</v>
			<v>1.087E-3</v>
			<v>1.07E-3</v>
			<v>9.183E-4</v>
			<v>8.402E-4</v>
			<v>7.263E-4</v>
			<v>6.795E-4</v>
			<v>7.442E-4</v>
			<v>7.733E-4</v>
			<v>7.745E-4</v>
			<v>7.622E-4</v>
			<v>7.405E-4</v>
			<v>9.05E-4</v>
			<v>9.972E-4</v>
			<v>9.792E-4</v>
			<v>9.144E-4</v>
			<v>8.798E-4</v>
			<v>9.079E-4</v>
			<v>9.354E-4</v>
			<v>1.05E-3</v>
			<v>1.135E-3</v>
			<v>1.013E-3</v>
			<v>9.214E-4</v>
			<v>9.791E-4</v>
			<v>9.899E-4</v>
			<v>8.521E-4</v>
			<v>7.665E-4</v>
			<v>7.967E-4</v>
			<v>9.182E-4</v>
			<v>1.018E-3</v>
			<v>1.066E-3</v>
			<v>1.043E-3</v>
			<v>1.002E-3</v>
			<v>1.038E-3</v>
			<v>9.984E-4</v>
			<v>9.291E-4</v>
			<v>9.091E-4</v>
			<v>9.427E-4</v>
			<v>9.49E-4</v>
			<v>1.003E-3</v>
			<v>1.007E-3</v>
			<v>9.861E-4</v>
			<v>9.476E-4</v>
			<v>9.114E-4</v>
			<v>8.946E-4</v>
			<v>9.254E-4</v>
			<v>9.44E-4</v>
			<v>8.909E-4</v>
			<v>8.797E-4</v>
			<v>8.677E-4</v>
			<v>8.253E-4</v>
			<v>7.926E-4</v>
			<v>8.435E-4</v>
			<v>8.431E-4</v>
			<v>7.788E-4</v>
			<v>7.959E-4</v>
			<v>7.976E-4</v>
			<v>7.797E-4</v>
			<v>8.659E-4</v>
			<v>8.241E-4</v>
			<v>7.961E-4</v>
			<v>7.834E-4</v>
			<v>7.511E-4</v>
			<v>7.332E-4</v>
			<v>7.826E-4</v>
			<v>8.17E-4</v>
			<v>8.319E-4</v>
			<v>8.203E-4</v>
			<v>7.871E-4</v>
			<v>7.15E-4</v>
			<v>6.565E-4</v>
			<v>6.514E-4</v>
			<v>6.847E-4</v>
			<v>6.886E-4</v>
			<v>6.16E-4</v>
			<v>6.265E-4</v>
			<v>6.552E-4</v>
			<v>6.662E-4</v>
			<v>6.525E-4</v>
			<v>6.1E-4</v>
			<v>5.994E-4</v>
			<v>6.283E-4</v>
			<v>6.738E-4</v>
			<v>5.984E-4</v>
			<v>5.825E-4</v>
			<v>6.1E-4</v>
			<v>6.095E-4</v>
			<v>5.868E-4</v>
			<v>5.938E-4</v>
			<v>6.972E-4</v>
			<v>7.529E-4</v>
			<v>6.24E-4</v>
			<v>5.353E-4</v>
			<v>5.744E-4</v>
			<v>6.228E-4</v>
			<v>5.88E-4</v>
			<v>6.114E-4</v>
			<v>6.09E-4</v>
			<v>6.142E-4</v>
			<v>6.331E-4</v>
		</feature>
		<feature>
			<name>Power Spectrum Overall Standard Deviation</name>
			<v>2.2E-2</v>
			<v>7.857E-2</v>
			<v>3.701E-1</v>
			<v>5.836E-1</v>
			<v>6.504E-1</v>
			<v>4.711E-1</v>
			<v>3.926E-1</v>
			<v>3.025E-1</v>
			<v>1.542E-1</v>
			<v>9.813E-2</v>
			<v>5.158E-2</v>
			<v>3.221E-2</v>
			<v>3.868E-2</v>
			<v>7.174E-2</v>
			<v>6.041E-2</v>
			<v>6.918E-2</v>
			<v>5.396E-2</v>
			<v>7.405E-2</v>
			<v>5.395E-2</v>
			<v>6.282E-2</v>
			<v>8.25E-2</v>
			<v>5.535E-2</v>
			<v>1.098E-1</v>
			<v>6.362E-2</v>
			<v>5.16E-2</v>
			<v>1.102E-1</v>
			<v>5.77E-2</v>
			<v>5.356E-2</v>
			<v>6.1E-2</v>
			<v>6.511E-2</v>
			<v>7.172E-2</v>
			<v>3.742E-2</v>
			<v>2.936E-2</v>
			<v>5.677E-2</v>
			<v>5.449E-2</v>
			<v>5.047E-2</v>
			<v>5.264E-2</v>
			<v>5.204E-2</v>
			<v>3.705E-2</v>
			<v>5.489E-2</v>
			<v>7.902E-2</v>
			<v>1.345E-1</v>
			<v>1.347E-1</v>
			<v>1.008E-1</v>
			<v>9.083E-2</v>
			<v>1.09E-1</v>
			<v>9.571E-2</v>
			<v>6.194E-2</v>
			<v>3.757E-2</v>
			<v>5.874E-2</v>
			<v>7.13E-2</v>
			<v>4.131E-2</v>
			<v>3.206E-2</v>
			<v>4.212E-2</v>
			<v>4.366E-2</v>
			<v>4.521E-2</v>
			<v>5.69E-2</v>
			<v>4.351E-2</v>
			<v>6.89E-2</v>
			<v>6.819E-2</v>
			<v>8.266E-2</v>
			<v>3.457E-2</v>
			<v>3.959E-2</v>
			<v>5.641E-2</v>
			<v>4.852E-2</v>
			<v>4.391E-2</v>
			<v>4.041E-2</v>
			<v>5.654E-2</v>
			<v>4.701E-2</v>
			<v>4.486E-2</v>
			<v>4.364E-2</v>
			<v>2.788E-2</v>
			<v>5.221E-2</v>
			<v>4.757E-2</v>
			<v>4.25E-2</v>
			<v>3.732E-2</v>
			<v>3.415E-2</v>
			<v>2.733E-2</v>
			<v>2.971E-2</v>
			<v>2.771E-2</v>
			<v>2.394E-2</v>
			<v>2.333E-2</v>
			<v>2.342E-2</v>
			<v>2.923E-2</v>
			<v>2.777E-2</v>
			<v>2.255E-2</v>
			<v>1.694E-2</v>
			<v>1.812E-2</v>
			<v>2.07E-2</v>
			<v>1.99E-2</v>
			<v>1.992E-2</v>
			<v>1.301E-2</v>
			<v>1.177E-2</v>
			<v>7.964E-3</v>
			<v>6.701E-3</v>
			<v>5.883E-3</v>
			<v>4.825E-3</v>
			<v>4.577E-3</v>
			<v>5.124E-3</v>
			<v>5.782E-3</v>
			<v>5.465E-3</v>
			<v>5.728E-3</v>
			<v>4.9E-3</v>
			<v>4.74E-3</v>
			<v>3.822E-3</v>
			<v>3.333E-3</v>
			<v>3.936E-3</v>
			<v>4.572E-3</v>
			<v>4.734E-3</v>
			<v>5.441E-3</v>
			<v>5.801E-3</v>
			<v>5.757E-3</v>
			<v>8.525E-3</v>
			<v>8.108E-3</v>
			<v>6.324E-3</v>
			<v>6.382E-3</v>
			<v>7.45E-3</v>
			<v>9.408E-3</v>
			<v>9.342E-3</v>
			<v>9.926E-3</v>
			<v>9.128E-3</v>
			<v>1.032E-2</v>
			<v>9.7E-3</v>
			<v>8.693E-3</v>
			<v>7.623E-3</v>
			<v>9.114E-3</v>
			<v>1.283E-2</v>
			<v>1.239E-2</v>
			<v>1.193E-2</v>
			<v>9.471E-3</v>
			<v>8.404E-3</v>
			<v>8.792E-3</v>
			<v>7.57E-3</v>
			<v>5.922E-3</v>
			<v>5.848E-3</v>
			<v>5.988E-3</v>
			<v>3.696E-3</v>
			<v>3.482E-3</v>
			<v>4.462E-3</v>
			<v>4.15E-3</v>
			<v>3.713E-3</v>
			<v>4.456E-3</v>
			<v>4.704E-3</v>
			<v>4.685E-3</v>
			<v>3.219E-3</v>
			<v>2.627E-3</v>
			<v>2.928E-3</v>
			<v>1.863E-3</v>
			<v>1.855E-3</v>
			<v>2.295E-3</v>
			<v>2.919E-3</v>
			<v>3.239E-3</v>
			<v>2.402E-3</v>
			<v>1.766E-3</v>
			<v>1.823E-3</v>
			<v>2.122E-3</v>
			<v>2.349E-3</v>
			<v>4.698E-3</v>
			<v>3.778E-3</v>
			<v>2.491E-3</v>
			<v>2.322E-3</v>
			<v>1.611E-3</v>
			<v>1.394E-3</v>
			<v>1.622E-3</v>
			<v>1.765E-3</v>
			<v>1.841E-3</v>
			<v>1.909E-3</v>
			<v>1.782E-3</v>
			<v>2.282E-3</v>
			<v>2.899E-3</v>
			<v>3.367E-3</v>
			<v>2.937E-3</v>
			<v>2.212E-3</v>
			<v>2.277E-3</v>
			<v>2.379E-3</v>
			<v>3.106E-3</v>
			<v>3.258E-3</v>
			<v>2.922E-3</v>
			<v>2.522E-3</v>
			<v>2.57E-3</v>
			<v>2.754E-3</v>
			<v>2.2E-3</v>
			<v>1.964E-3</v>
			<v>2.06E-3</v>
			<v>2.989E-3</v>
			<v>3.189E-3</v>
			<v>3.463E-3</v>
			<v>3.066E-3</v>
			<v>3.046E-3</v>
			<v>3.482E-3</v>
			<v>3.258E-3</v>
			<v>3.053E-3</v>
			<v>2.726E-3</v>
			<v>3.441E-3</v>
			<v>2.887E-3</v>
			<v>3.386E-3</v>
			<v>3.019E-3</v>
			<v>3.119E-3</v>
			<v>3.265E-3</v>
			<v>3.033E-3</v>
			<v>2.627E-3</v>
			<v>2.768E-3</v>
			<v>2.993E-3</v>
			<v>2.315E-3</v>
			<v>2.112E-3</v>
			<v>2.143E-3</v>
			<v>2.344E-3</v>
			<v>1.961E-3</v>
			<v>2.129E-3</v>
			<v>1.947E-3</v>
			<v>1.694E-3</v>
			<v>2.207E-3</v>
			<v>2.72E-3</v>
			<v>1.818E-3</v>
			<v>2.112E-3</v>
			<v>2.128E-3</v>
			<v>2.206E-3</v>
			<v>2.149E-3</v>
			<v>1.864E-3</v>
			<v>1.636E-3</v>
			<v>1.896E-3</v>
			<v>2.119E-3</v>
			<v>2.12E-3</v>
			<v>2.009E-3</v>
			<v>1.757E-3</v>
			<v>1.495E-3</v>
			<v>1.221E-3</v>
			<v>1.334E-3</v>
			<v>1.544E-3</v>
			<v>1.521E-3</v>
			<v>1.101E-3</v>
			<v>1.062E-3</v>
			<v>1.278E-3</v>
			<v>1.398E-3</v>
			<v>1.322E-3</v>
			<v>1.131E-3</v>
			<v>1.232E-3</v>
			<v>1.142E-3</v>
			<v>1.197E-3</v>
			<v>9.617E-4</v>
			<v>1.057E-3</v>
			<v>1.227E-3</v>
			<v>1.221E-3</v>
			<v>1.008E-3</v>
			<v>1.096E-3</v>
			<v>1.669E-3</v>
			<v>1.847E-3</v>
			<v>1.084E-3</v>
			<v>8.771E-4</v>
			<v>1.213E-3</v>
			<v>1.275E-3</v>
			<v>1.122E-3</v>
			<v>1.228E-3</v>
			<v>1.127E-3</v>
			<v>1.32E-3</v>
			<v>2.061E-3</v>
		</feature>
		<feature>
			<name>FFT Bin Frequency Labels Overall Standard Deviation</name>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
		</feature>
		<feature>
			<name>Spectral Centroid Overall Standard Deviation</name>
			<v>1.857E1</v>
		</feature>
		<feature>
			<name>Spectral Rolloff Point Overall Standard Deviation</name>
			<v>1.488E-1</v>
		</feature>
		<feature>
			<name>Spectral Flux Overall Standard Deviation</name>
			<v>3.659E-3</v>
		</feature>
		<feature>
			<name>Compactness Overall Standard Deviation</name>
			<v>2.357E2</v>
		</feature>
		<feature>
			<name>Spectral Variability Overall Standard Deviation</name>
			<v>2.135E-3</v>
		</feature>
		<feature>
			<name>Root Mean Square Overall Standard Deviation</name>
			<v>8.644E-2</v>
		</feature>
		<feature>
			<name>Fraction Of Low Energy Windows Overall Standard Deviation</name>
			<v>6.408E-2</v>
		</feature>
		<feature>
			<name>Zero Crossings Overall Standard Deviation</name>
			<v>3.497E1</v>
		</feature>
		<feature>
			<name>Beat Histogram Overall Standard Deviation</name>
			<v>3.547E0</v>
			<v>3.507E0</v>
			<v>3.492E0</v>
			<v>3.507E0</v>
			<v>3.518E0</v>
			<v>3.541E0</v>
			<v>3.554E0</v>
			<v>3.481E0</v>
			<v>3.449E0</v>
			<v>3.444E0</v>
			<v>3.428E0</v>
			<v>3.424E0</v>
			<v>3.451E0</v>
			<v>3.521E0</v>
			<v>3.503E0</v>
			<v>3.408E0</v>
			<v>3.351E0</v>
			<v>3.319E0</v>
			<v>3.299E0</v>
			<v>3.294E0</v>
			<v>3.309E0</v>
			<v>3.323E0</v>
			<v>3.267E0</v>
			<v>3.24E0</v>
			<v>3.248E0</v>
			<v>3.234E0</v>
			<v>3.209E0</v>
			<v>3.214E0</v>
			<v>3.261E0</v>
			<v>3.257E0</v>
			<v>3.192E0</v>
			<v>3.142E0</v>
			<v>3.114E0</v>
			<v>3.106E0</v>
			<v>3.114E0</v>
			<v>3.134E0</v>
			<v>3.144E0</v>
			<v>3.098E0</v>
			<v>3.053E0</v>
			<v>3.039E0</v>
			<v>3.036E0</v>
			<v>3.022E0</v>
			<v>3.022E0</v>
			<v>3.063E0</v>
			<v>3.074E0</v>
			<v>3.024E0</v>
			<v>2.963E0</v>
			<v>2.923E0</v>
			<v>2.9E0</v>
			<v>2.892E0</v>
			<v>2.91E0</v>
			<v>2.925E0</v>
			<v>2.888E0</v>
			<v>2.838E0</v>
			<v>2.809E0</v>
			<v>2.803E0</v>
			<v>2.786E0</v>
			<v>2.77E0</v>
			<v>2.788E0</v>
			<v>2.789E0</v>
			<v>2.748E0</v>
			<v>2.698E0</v>
			<v>2.66E0</v>
			<v>2.637E0</v>
			<v>2.625E0</v>
			<v>2.64E0</v>
			<v>2.656E0</v>
			<v>2.618E0</v>
			<v>2.564E0</v>
			<v>2.533E0</v>
			<v>2.525E0</v>
			<v>2.526E0</v>
			<v>2.53E0</v>
			<v>2.556E0</v>
			<v>2.575E0</v>
			<v>2.545E0</v>
			<v>2.503E0</v>
			<v>2.458E0</v>
			<v>2.424E0</v>
			<v>2.4E0</v>
			<v>2.396E0</v>
			<v>2.41E0</v>
			<v>2.389E0</v>
			<v>2.343E0</v>
			<v>2.303E0</v>
			<v>2.288E0</v>
			<v>2.288E0</v>
			<v>2.279E0</v>
			<v>2.285E0</v>
			<v>2.29E0</v>
			<v>2.264E0</v>
			<v>2.224E0</v>
			<v>2.191E0</v>
			<v>2.163E0</v>
			<v>2.147E0</v>
			<v>2.146E0</v>
			<v>2.167E0</v>
			<v>2.16E0</v>
			<v>2.117E0</v>
			<v>2.08E0</v>
			<v>2.065E0</v>
			<v>2.062E0</v>
			<v>2.063E0</v>
			<v>2.073E0</v>
			<v>2.08E0</v>
			<v>2.052E0</v>
			<v>2.015E0</v>
			<v>1.975E0</v>
			<v>1.937E0</v>
			<v>1.907E0</v>
			<v>1.893E0</v>
			<v>1.899E0</v>
			<v>1.893E0</v>
			<v>1.864E0</v>
			<v>1.829E0</v>
			<v>1.81E0</v>
			<v>1.806E0</v>
			<v>1.809E0</v>
			<v>1.809E0</v>
			<v>1.806E0</v>
			<v>1.783E0</v>
			<v>1.75E0</v>
			<v>1.722E0</v>
			<v>1.699E0</v>
			<v>1.68E0</v>
			<v>1.671E0</v>
			<v>1.678E0</v>
			<v>1.682E0</v>
			<v>1.661E0</v>
			<v>1.627E0</v>
			<v>1.602E0</v>
			<v>1.591E0</v>
			<v>1.586E0</v>
			<v>1.586E0</v>
			<v>1.586E0</v>
			<v>1.57E0</v>
			<v>1.542E0</v>
			<v>1.516E0</v>
			<v>1.495E0</v>
			<v>1.471E0</v>
			<v>1.454E0</v>
			<v>1.451E0</v>
			<v>1.447E0</v>
			<v>1.432E0</v>
			<v>1.405E0</v>
			<v>1.382E0</v>
			<v>1.367E0</v>
			<v>1.361E0</v>
			<v>1.363E0</v>
			<v>1.359E0</v>
			<v>1.339E0</v>
			<v>1.312E0</v>
			<v>1.282E0</v>
			<v>1.261E0</v>
			<v>1.242E0</v>
			<v>1.227E0</v>
			<v>1.224E0</v>
			<v>1.221E0</v>
			<v>1.211E0</v>
			<v>1.188E0</v>
			<v>1.165E0</v>
			<v>1.151E0</v>
			<v>1.142E0</v>
			<v>1.141E0</v>
			<v>1.144E0</v>
			<v>1.132E0</v>
			<v>1.107E0</v>
			<v>1.08E0</v>
			<v>1.06E0</v>
			<v>1.042E0</v>
			<v>1.02E0</v>
		</feature>
		<feature>
			<name>Beat Histogram Bin Labels Overall Standard Deviation</name>
			<v>2.274E-12</v>
			<v>5.969E-13</v>
			<v>3.686E-11</v>
			<v>0E0</v>
			<v>2.356E-11</v>
			<v>3.038E-11</v>
			<v>4.983E-11</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>1.455E-11</v>
			<v>3.212E-11</v>
			<v>9.237E-12</v>
			<v>7.106E-12</v>
			<v>0E0</v>
			<v>1.441E-11</v>
			<v>0E0</v>
			<v>1.839E-11</v>
			<v>1.137E-12</v>
			<v>1.032E-11</v>
			<v>2.984E-13</v>
			<v>8.911E-12</v>
			<v>1.843E-11</v>
			<v>8.655E-12</v>
			<v>0E0</v>
			<v>1.309E-11</v>
			<v>1.178E-11</v>
			<v>1.212E-11</v>
			<v>1.519E-11</v>
			<v>1.465E-11</v>
			<v>2.491E-11</v>
			<v>8.939E-12</v>
			<v>0E0</v>
			<v>1.428E-11</v>
			<v>0E0</v>
			<v>6.31E-12</v>
			<v>7.276E-12</v>
			<v>1.268E-11</v>
			<v>1.606E-11</v>
			<v>1.649E-11</v>
			<v>4.619E-12</v>
			<v>1.704E-11</v>
			<v>3.553E-12</v>
			<v>5.329E-12</v>
			<v>0E0</v>
			<v>1.327E-11</v>
			<v>7.205E-12</v>
			<v>1.226E-11</v>
			<v>0E0</v>
			<v>1.064E-11</v>
			<v>9.195E-12</v>
			<v>3.29E-12</v>
			<v>5.685E-13</v>
			<v>3.048E-12</v>
			<v>5.159E-12</v>
			<v>1.897E-12</v>
			<v>1.492E-13</v>
			<v>9.024E-13</v>
			<v>4.455E-12</v>
			<v>0E0</v>
			<v>9.216E-12</v>
			<v>3.134E-12</v>
			<v>4.327E-12</v>
			<v>8.562E-12</v>
			<v>0E0</v>
			<v>3.659E-12</v>
			<v>6.544E-12</v>
			<v>8.491E-12</v>
			<v>5.891E-12</v>
			<v>1.32E-11</v>
			<v>6.061E-12</v>
			<v>8.399E-12</v>
			<v>7.596E-12</v>
			<v>4.455E-12</v>
			<v>7.326E-12</v>
			<v>7.923E-12</v>
			<v>1.246E-11</v>
			<v>6.274E-12</v>
			<v>4.469E-12</v>
			<v>8.498E-12</v>
			<v>0E0</v>
			<v>8.392E-12</v>
			<v>7.141E-12</v>
			<v>3.269E-12</v>
			<v>0E0</v>
			<v>5.614E-13</v>
			<v>3.155E-12</v>
			<v>9.82E-12</v>
			<v>3.638E-12</v>
			<v>8.172E-12</v>
			<v>6.338E-12</v>
			<v>7.425E-12</v>
			<v>8.029E-12</v>
			<v>4.803E-12</v>
			<v>8.243E-12</v>
			<v>2.871E-12</v>
			<v>2.309E-12</v>
			<v>5.052E-12</v>
			<v>8.52E-12</v>
			<v>8.058E-12</v>
			<v>1.776E-12</v>
			<v>8.754E-12</v>
			<v>2.665E-12</v>
			<v>4.363E-12</v>
			<v>0E0</v>
			<v>2.583E-12</v>
			<v>6.633E-12</v>
			<v>6.519E-12</v>
			<v>3.603E-12</v>
			<v>0E0</v>
			<v>6.129E-12</v>
			<v>8.442E-12</v>
			<v>0E0</v>
			<v>5.692E-12</v>
			<v>5.322E-12</v>
			<v>2.778E-12</v>
			<v>4.597E-12</v>
			<v>4.278E-12</v>
			<v>1.645E-12</v>
			<v>3.574E-12</v>
			<v>2.842E-13</v>
			<v>2.999E-12</v>
			<v>1.524E-12</v>
			<v>3.77E-12</v>
			<v>2.579E-12</v>
			<v>3.766E-12</v>
			<v>9.486E-13</v>
			<v>1.748E-12</v>
			<v>7.461E-14</v>
			<v>5.113E-12</v>
			<v>4.512E-13</v>
			<v>3.553E-13</v>
			<v>2.228E-12</v>
			<v>8.136E-13</v>
			<v>0E0</v>
			<v>5.685E-14</v>
			<v>4.608E-12</v>
			<v>1.958E-12</v>
			<v>1.567E-12</v>
			<v>4.104E-12</v>
			<v>2.164E-12</v>
			<v>9.131E-13</v>
			<v>4.281E-12</v>
			<v>4.651E-12</v>
			<v>0E0</v>
			<v>1.435E-12</v>
			<v>1.83E-12</v>
			<v>5.72E-13</v>
			<v>3.272E-12</v>
			<v>1.3E-12</v>
			<v>4.246E-12</v>
			<v>6.033E-12</v>
			<v>2.945E-12</v>
			<v>2.821E-12</v>
			<v>6.598E-12</v>
			<v>9.344E-13</v>
			<v>3.031E-12</v>
			<v>4.7E-12</v>
			<v>4.199E-12</v>
			<v>2.721E-12</v>
			<v>3.798E-12</v>
			<v>1.624E-12</v>
			<v>2.228E-12</v>
			<v>3.279E-12</v>
			<v>3.663E-12</v>
			<v>3.688E-12</v>
			<v>3.961E-12</v>
			<v>1.872E-12</v>
			<v>6.228E-12</v>
			<v>2.473E-12</v>
			<v>3.137E-12</v>
			<v>1.499E-12</v>
		</feature>
		<feature>
			<name>Strongest Beat Overall Standard Deviation</name>
			<v>3.008E1</v>
		</feature>
		<feature>
			<name>Beat Sum Overall Standard Deviation</name>
			<v>3.951E2</v>
		</feature>
		<feature>
			<name>Strength Of Strongest Beat Overall Standard Deviation</name>
			<v>1.567E-3</v>
		</feature>
		<feature>
			<name>Strongest Frequency Via Zero Crossings Overall Standard Deviation</name>
			<v>5.465E2</v>
		</feature>
		<feature>
			<name>Strongest Frequency Via Spectral Centroid Overall Standard Deviation</name>
			<v>5.802E2</v>
		</feature>
		<feature>
			<name>Strongest Frequency Via FFT Maximum Overall Standard Deviation</name>
			<v>5.986E2</v>
		</feature>
		<feature>
			<name>MFCC Overall Standard Deviation</name>
			<v>7.354E1</v>
			<v>4.962E0</v>
			<v>2.862E0</v>
			<v>2.798E0</v>
			<v>2.398E0</v>
			<v>2.206E0</v>
			<v>2E0</v>
			<v>1.947E0</v>
			<v>1.849E0</v>
			<v>1.787E0</v>
			<v>1.642E0</v>
			<v>1.57E0</v>
			<v>1.486E0</v>
		</feature>
		<feature>
			<name>ConstantQ Overall Standard Deviation</name>
			<v>8.241E-2</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>6.116E-3</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
		</feature>
		<feature>
			<name>LPC Overall Standard Deviation</name>
			<v>1.432E-1</v>
			<v>3.075E-1</v>
			<v>1.91E-1</v>
			<v>1.517E-1</v>
			<v>1.556E-1</v>
			<v>1.354E-1</v>
			<v>1.295E-1</v>
			<v>1.353E-1</v>
			<v>1.113E-1</v>
			<v>0E0</v>
		</feature>
		<feature>
			<name>Method of Moments Overall Standard Deviation</name>
			<v>2.964E-1</v>
			<v>1.732E1</v>
			<v>1.263E3</v>
			<v>9.772E4</v>
			<v>1.82E7</v>
		</feature>
		<feature>
			<name>Peak Detection Overall Standard Deviation</name>
		</feature>
		<feature>
			<name>Partial Based Spectral Centroid Overall Standard Deviation</name>
			<v>NaN</v>
		</feature>
		<feature>
			<name>Partial Based Spectral Flux Overall Standard Deviation</name>
			<v>NaN</v>
		</feature>
		<feature>
			<name>Peak Based Spectral Smoothness Overall Standard Deviation</name>
			<v>6.245E1</v>
		</feature>
		<feature>
			<name>Relative Difference Function Overall Standard Deviation</name>
			<v>7.353E0</v>
		</feature>
		<feature>
			<name>Area Method of Moments Overall Standard Deviation</name>
			<v>2.492E0</v>
			<v>3.914E5</v>
			<v>5.533E6</v>
			<v>2.738E12</v>
			<v>3.87E13</v>
			<v>5.472E14</v>
			<v>3.836E19</v>
			<v>3.489E14</v>
			<v>4.933E15</v>
			<v>1.084E23</v>
		</feature>
		<feature>
			<name>Area Method of Moments of MFCCs Overall Standard Deviation</name>
			<v>2.492E0</v>
			<v>3.914E5</v>
			<v>5.533E6</v>
			<v>2.738E12</v>
			<v>3.87E13</v>
			<v>5.472E14</v>
			<v>3.836E19</v>
			<v>3.489E14</v>
			<v>4.933E15</v>
			<v>1.084E23</v>
		</feature>
		<feature>
			<name>Area Method of Moments of Log of ConstantQ transform Overall Standard Deviation</name>
			<v>2.492E0</v>
			<v>3.914E5</v>
			<v>5.533E6</v>
			<v>2.738E12</v>
			<v>3.87E13</v>
			<v>5.472E14</v>
			<v>3.836E19</v>
			<v>3.489E14</v>
			<v>4.933E15</v>
			<v>1.084E23</v>
		</feature>
		<feature>
			<name>Area Method of Moments of ConstantQ-based MFCCs Overall Standard Deviation</name>
			<v>2.492E0</v>
			<v>3.914E5</v>
			<v>5.533E6</v>
			<v>2.738E12</v>
			<v>3.87E13</v>
			<v>5.472E14</v>
			<v>3.836E19</v>
			<v>3.489E14</v>
			<v>4.933E15</v>
			<v>1.084E23</v>
		</feature>
		<feature>
			<name>Magnitude Spectrum Overall Average</name>
			<v>2.562E-3</v>
			<v>4.305E-3</v>
			<v>1.13E-2</v>
			<v>1.607E-2</v>
			<v>1.811E-2</v>
			<v>1.686E-2</v>
			<v>1.34E-2</v>
			<v>9.887E-3</v>
			<v>7.682E-3</v>
			<v>6.461E-3</v>
			<v>4.339E-3</v>
			<v>3.926E-3</v>
			<v>4.378E-3</v>
			<v>4.868E-3</v>
			<v>4.664E-3</v>
			<v>4.072E-3</v>
			<v>3.663E-3</v>
			<v>3.92E-3</v>
			<v>3.734E-3</v>
			<v>3.92E-3</v>
			<v>3.086E-3</v>
			<v>2.644E-3</v>
			<v>4.452E-3</v>
			<v>3.838E-3</v>
			<v>3.098E-3</v>
			<v>4.572E-3</v>
			<v>3.455E-3</v>
			<v>2.674E-3</v>
			<v>3.376E-3</v>
			<v>3.524E-3</v>
			<v>3.581E-3</v>
			<v>2.845E-3</v>
			<v>2.431E-3</v>
			<v>3.358E-3</v>
			<v>3.361E-3</v>
			<v>2.243E-3</v>
			<v>2.094E-3</v>
			<v>2.354E-3</v>
			<v>2.229E-3</v>
			<v>2.19E-3</v>
			<v>2.474E-3</v>
			<v>2.718E-3</v>
			<v>3.139E-3</v>
			<v>2.626E-3</v>
			<v>3.086E-3</v>
			<v>3.168E-3</v>
			<v>2.066E-3</v>
			<v>1.826E-3</v>
			<v>1.622E-3</v>
			<v>2.574E-3</v>
			<v>4.011E-3</v>
			<v>2.928E-3</v>
			<v>1.744E-3</v>
			<v>1.882E-3</v>
			<v>1.607E-3</v>
			<v>1.921E-3</v>
			<v>3.001E-3</v>
			<v>2.674E-3</v>
			<v>2.102E-3</v>
			<v>2.443E-3</v>
			<v>2.267E-3</v>
			<v>1.752E-3</v>
			<v>1.983E-3</v>
			<v>2.287E-3</v>
			<v>1.888E-3</v>
			<v>1.673E-3</v>
			<v>2.219E-3</v>
			<v>3.161E-3</v>
			<v>2.786E-3</v>
			<v>1.927E-3</v>
			<v>1.845E-3</v>
			<v>1.729E-3</v>
			<v>1.516E-3</v>
			<v>1.622E-3</v>
			<v>1.843E-3</v>
			<v>2.483E-3</v>
			<v>2.47E-3</v>
			<v>1.977E-3</v>
			<v>2.112E-3</v>
			<v>2.158E-3</v>
			<v>2.034E-3</v>
			<v>2.003E-3</v>
			<v>2.097E-3</v>
			<v>2.115E-3</v>
			<v>2.32E-3</v>
			<v>2.08E-3</v>
			<v>1.639E-3</v>
			<v>1.695E-3</v>
			<v>1.911E-3</v>
			<v>2.1E-3</v>
			<v>2.13E-3</v>
			<v>1.699E-3</v>
			<v>1.595E-3</v>
			<v>1.412E-3</v>
			<v>1.308E-3</v>
			<v>1.283E-3</v>
			<v>1.175E-3</v>
			<v>1.127E-3</v>
			<v>1.2E-3</v>
			<v>1.214E-3</v>
			<v>1.273E-3</v>
			<v>1.447E-3</v>
			<v>1.275E-3</v>
			<v>1.054E-3</v>
			<v>9.186E-4</v>
			<v>8.873E-4</v>
			<v>9.343E-4</v>
			<v>1.01E-3</v>
			<v>1.067E-3</v>
			<v>1.236E-3</v>
			<v>1.242E-3</v>
			<v>1.218E-3</v>
			<v>1.414E-3</v>
			<v>1.457E-3</v>
			<v>1.178E-3</v>
			<v>1.135E-3</v>
			<v>1.116E-3</v>
			<v>1.129E-3</v>
			<v>1.11E-3</v>
			<v>9.873E-4</v>
			<v>9.887E-4</v>
			<v>9.048E-4</v>
			<v>8.621E-4</v>
			<v>8.75E-4</v>
			<v>8.51E-4</v>
			<v>9.408E-4</v>
			<v>1.105E-3</v>
			<v>1.086E-3</v>
			<v>9.075E-4</v>
			<v>7.952E-4</v>
			<v>7.809E-4</v>
			<v>8.218E-4</v>
			<v>8.917E-4</v>
			<v>8.742E-4</v>
			<v>9.124E-4</v>