<?xml version="1.0"?>
<!DOCTYPE feature_vector_file [
   <!ELEMENT feature_vector_file (comments, data_set+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT data_set (data_set_id, section*, feature*)>
   <!ELEMENT data_set_id (#PCDATA)>
   <!ELEMENT section (feature+)>
   <!ATTLIST section start CDATA ""
                     stop CDATA "">
   <!ELEMENT feature (name, v+)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT v (#PCDATA)>
]>

<feature_vector_file>

   <comments></comments>

	<data_set>
		<data_set_id>C:\Users\user\Desktop\New folder\Rock\wav\Baba O'Riley - The Who.wav</data_set_id>
		<feature>
			<name>Magnitude Spectrum Overall Standard Deviation</name>
			<v>4.335E-3</v>
			<v>1.917E-2</v>
			<v>3.485E-2</v>
			<v>3.252E-2</v>
			<v>2.396E-2</v>
			<v>2.607E-2</v>
			<v>3.111E-2</v>
			<v>1.638E-2</v>
			<v>1.645E-2</v>
			<v>1.385E-2</v>
			<v>1.48E-2</v>
			<v>2.097E-2</v>
			<v>1.713E-2</v>
			<v>1.581E-2</v>
			<v>1.731E-2</v>
			<v>1.69E-2</v>
			<v>1.095E-2</v>
			<v>1.486E-2</v>
			<v>9.449E-3</v>
			<v>8.524E-3</v>
			<v>9.186E-3</v>
			<v>8.077E-3</v>
			<v>1.012E-2</v>
			<v>1.135E-2</v>
			<v>7.022E-3</v>
			<v>9.253E-3</v>
			<v>1.058E-2</v>
			<v>7.324E-3</v>
			<v>1.468E-2</v>
			<v>1.437E-2</v>
			<v>9.896E-3</v>
			<v>7.145E-3</v>
			<v>7.533E-3</v>
			<v>1.019E-2</v>
			<v>1.55E-2</v>
			<v>9.984E-3</v>
			<v>4.434E-3</v>
			<v>3.629E-3</v>
			<v>5.842E-3</v>
			<v>6.097E-3</v>
			<v>7.196E-3</v>
			<v>7.107E-3</v>
			<v>5.101E-3</v>
			<v>5.758E-3</v>
			<v>5.372E-3</v>
			<v>5.865E-3</v>
			<v>5.588E-3</v>
			<v>3.928E-3</v>
			<v>3.03E-3</v>
			<v>2.914E-3</v>
			<v>5.273E-3</v>
			<v>6.766E-3</v>
			<v>4.532E-3</v>
			<v>3.68E-3</v>
			<v>3.519E-3</v>
			<v>3.721E-3</v>
			<v>5.025E-3</v>
			<v>6.09E-3</v>
			<v>5.549E-3</v>
			<v>3.973E-3</v>
			<v>4.066E-3</v>
			<v>3.69E-3</v>
			<v>3.105E-3</v>
			<v>3.96E-3</v>
			<v>4.716E-3</v>
			<v>4.78E-3</v>
			<v>4.52E-3</v>
			<v>4.908E-3</v>
			<v>6.162E-3</v>
			<v>5.909E-3</v>
			<v>4.212E-3</v>
			<v>3.639E-3</v>
			<v>3.68E-3</v>
			<v>2.842E-3</v>
			<v>2.429E-3</v>
			<v>2.61E-3</v>
			<v>3.474E-3</v>
			<v>4.29E-3</v>
			<v>3.546E-3</v>
			<v>3.392E-3</v>
			<v>3.69E-3</v>
			<v>3.579E-3</v>
			<v>2.883E-3</v>
			<v>2.482E-3</v>
			<v>2.575E-3</v>
			<v>3.691E-3</v>
			<v>4.305E-3</v>
			<v>3.606E-3</v>
			<v>3.468E-3</v>
			<v>3.51E-3</v>
			<v>3.726E-3</v>
			<v>4.329E-3</v>
			<v>3.808E-3</v>
			<v>2.952E-3</v>
			<v>2.438E-3</v>
			<v>2.178E-3</v>
			<v>2.38E-3</v>
			<v>2.141E-3</v>
			<v>2.072E-3</v>
			<v>2.352E-3</v>
			<v>2.593E-3</v>
			<v>2.443E-3</v>
			<v>3.403E-3</v>
			<v>3.519E-3</v>
			<v>2.09E-3</v>
			<v>2.044E-3</v>
			<v>2.583E-3</v>
			<v>2.986E-3</v>
			<v>2.408E-3</v>
			<v>1.674E-3</v>
			<v>1.555E-3</v>
			<v>1.745E-3</v>
			<v>2.138E-3</v>
			<v>2.51E-3</v>
			<v>3.171E-3</v>
			<v>3.061E-3</v>
			<v>2.671E-3</v>
			<v>2.179E-3</v>
			<v>2.21E-3</v>
			<v>2.778E-3</v>
			<v>3.142E-3</v>
			<v>2.445E-3</v>
			<v>2.108E-3</v>
			<v>1.998E-3</v>
			<v>1.981E-3</v>
			<v>2.186E-3</v>
			<v>2.435E-3</v>
			<v>2.534E-3</v>
			<v>2.57E-3</v>
			<v>2.007E-3</v>
			<v>1.479E-3</v>
			<v>1.507E-3</v>
			<v>1.697E-3</v>
			<v>1.724E-3</v>
			<v>1.53E-3</v>
			<v>1.357E-3</v>
			<v>1.475E-3</v>
			<v>1.687E-3</v>
			<v>1.426E-3</v>
			<v>1.369E-3</v>
			<v>1.458E-3</v>
			<v>1.548E-3</v>
			<v>1.344E-3</v>
			<v>1.297E-3</v>
			<v>1.213E-3</v>
			<v>1.007E-3</v>
			<v>1.104E-3</v>
			<v>1.303E-3</v>
			<v>1.383E-3</v>
			<v>1.27E-3</v>
			<v>1.235E-3</v>
			<v>1.356E-3</v>
			<v>1.63E-3</v>
			<v>1.589E-3</v>
			<v>1.248E-3</v>
			<v>1.06E-3</v>
			<v>9.675E-4</v>
			<v>1.043E-3</v>
			<v>1.198E-3</v>
			<v>1.538E-3</v>
			<v>1.637E-3</v>
			<v>1.504E-3</v>
			<v>1.467E-3</v>
			<v>1.169E-3</v>
			<v>9.885E-4</v>
			<v>1.034E-3</v>
			<v>1.178E-3</v>
			<v>1.228E-3</v>
			<v>1.045E-3</v>
			<v>8.803E-4</v>
			<v>8.253E-4</v>
			<v>8.777E-4</v>
			<v>1.027E-3</v>
			<v>1.179E-3</v>
			<v>1.035E-3</v>
			<v>1.171E-3</v>
			<v>1.152E-3</v>
			<v>8.873E-4</v>
			<v>8.596E-4</v>
			<v>9.96E-4</v>
			<v>1.149E-3</v>
			<v>9.597E-4</v>
			<v>1.217E-3</v>
			<v>1.603E-3</v>
			<v>1.42E-3</v>
			<v>1.282E-3</v>
			<v>1.085E-3</v>
			<v>1.007E-3</v>
			<v>1.073E-3</v>
			<v>1.058E-3</v>
			<v>1.036E-3</v>
			<v>1.168E-3</v>
			<v>1.322E-3</v>
			<v>1.365E-3</v>
			<v>1.515E-3</v>
			<v>1.6E-3</v>
			<v>1.308E-3</v>
			<v>1.076E-3</v>
			<v>1.085E-3</v>
			<v>1.004E-3</v>
			<v>8.743E-4</v>
			<v>8.164E-4</v>
			<v>8.414E-4</v>
			<v>8.522E-4</v>
			<v>8.785E-4</v>
			<v>9.141E-4</v>
			<v>8.4E-4</v>
			<v>8.845E-4</v>
			<v>9.424E-4</v>
			<v>9.379E-4</v>
			<v>9.185E-4</v>
			<v>9.801E-4</v>
			<v>1.002E-3</v>
			<v>1.077E-3</v>
			<v>1.059E-3</v>
			<v>9.294E-4</v>
			<v>9.016E-4</v>
			<v>8.819E-4</v>
			<v>8.132E-4</v>
			<v>7.667E-4</v>
			<v>7.784E-4</v>
			<v>7.753E-4</v>
			<v>7.411E-4</v>
			<v>8.405E-4</v>
			<v>8.57E-4</v>
			<v>9.231E-4</v>
			<v>9.645E-4</v>
			<v>9.145E-4</v>
			<v>8.339E-4</v>
			<v>8.149E-4</v>
			<v>8.439E-4</v>
			<v>8.204E-4</v>
			<v>7.984E-4</v>
			<v>8.006E-4</v>
			<v>8.943E-4</v>
			<v>8.997E-4</v>
			<v>8.767E-4</v>
			<v>8.277E-4</v>
			<v>8.495E-4</v>
			<v>1.005E-3</v>
			<v>1.023E-3</v>
			<v>9.164E-4</v>
			<v>8.466E-4</v>
			<v>8.062E-4</v>
			<v>7.958E-4</v>
			<v>7.371E-4</v>
			<v>7.309E-4</v>
			<v>7.436E-4</v>
			<v>7.572E-4</v>
			<v>8.892E-4</v>
			<v>1.064E-3</v>
			<v>1.036E-3</v>
			<v>9.773E-4</v>
			<v>8.764E-4</v>
			<v>7.731E-4</v>
			<v>7.634E-4</v>
		</feature>
		<feature>
			<name>Power Spectrum Overall Standard Deviation</name>
			<v>4.771E-2</v>
			<v>5.9E-1</v>
			<v>2.017E0</v>
			<v>2.043E0</v>
			<v>1.215E0</v>
			<v>1.138E0</v>
			<v>1.69E0</v>
			<v>5.043E-1</v>
			<v>5.698E-1</v>
			<v>5.054E-1</v>
			<v>6.885E-1</v>
			<v>1.363E0</v>
			<v>8.488E-1</v>
			<v>8.799E-1</v>
			<v>1.129E0</v>
			<v>1.099E0</v>
			<v>3.999E-1</v>
			<v>5.857E-1</v>
			<v>2.612E-1</v>
			<v>2.641E-1</v>
			<v>2.488E-1</v>
			<v>2.085E-1</v>
			<v>3.629E-1</v>
			<v>3.98E-1</v>
			<v>2.219E-1</v>
			<v>2.577E-1</v>
			<v>3.669E-1</v>
			<v>2.09E-1</v>
			<v>7.199E-1</v>
			<v>6.213E-1</v>
			<v>3.186E-1</v>
			<v>1.602E-1</v>
			<v>2.06E-1</v>
			<v>2.823E-1</v>
			<v>6.434E-1</v>
			<v>3.176E-1</v>
			<v>1.428E-1</v>
			<v>6.201E-2</v>
			<v>1.282E-1</v>
			<v>1.676E-1</v>
			<v>1.877E-1</v>
			<v>1.802E-1</v>
			<v>1.367E-1</v>
			<v>1.752E-1</v>
			<v>2.021E-1</v>
			<v>1.795E-1</v>
			<v>1.641E-1</v>
			<v>1.133E-1</v>
			<v>4.617E-2</v>
			<v>3.268E-2</v>
			<v>2.108E-1</v>
			<v>3.391E-1</v>
			<v>9.384E-2</v>
			<v>8.236E-2</v>
			<v>4.492E-2</v>
			<v>8.103E-2</v>
			<v>1.219E-1</v>
			<v>1.405E-1</v>
			<v>1.313E-1</v>
			<v>7.997E-2</v>
			<v>6.004E-2</v>
			<v>4.417E-2</v>
			<v>4.94E-2</v>
			<v>9.316E-2</v>
			<v>1.286E-1</v>
			<v>1.328E-1</v>
			<v>1.166E-1</v>
			<v>1.211E-1</v>
			<v>1.511E-1</v>
			<v>1.337E-1</v>
			<v>9.204E-2</v>
			<v>6.014E-2</v>
			<v>6.875E-2</v>
			<v>4.083E-2</v>
			<v>2.383E-2</v>
			<v>2.289E-2</v>
			<v>3.313E-2</v>
			<v>4.862E-2</v>
			<v>5.406E-2</v>
			<v>5.516E-2</v>
			<v>4.982E-2</v>
			<v>5.466E-2</v>
			<v>3.016E-2</v>
			<v>2.752E-2</v>
			<v>3.036E-2</v>
			<v>4.437E-2</v>
			<v>5.401E-2</v>
			<v>4.158E-2</v>
			<v>4.905E-2</v>
			<v>4.872E-2</v>
			<v>5.079E-2</v>
			<v>6.124E-2</v>
			<v>4.262E-2</v>
			<v>2.997E-2</v>
			<v>2.111E-2</v>
			<v>1.292E-2</v>
			<v>1.415E-2</v>
			<v>1.269E-2</v>
			<v>1.155E-2</v>
			<v>1.696E-2</v>
			<v>2.169E-2</v>
			<v>1.78E-2</v>
			<v>2.952E-2</v>
			<v>3.138E-2</v>
			<v>1.082E-2</v>
			<v>1.139E-2</v>
			<v>2.354E-2</v>
			<v>3.153E-2</v>
			<v>1.82E-2</v>
			<v>8.006E-3</v>
			<v>5.998E-3</v>
			<v>6.89E-3</v>
			<v>1.124E-2</v>
			<v>2.218E-2</v>
			<v>3.383E-2</v>
			<v>2.667E-2</v>
			<v>2.377E-2</v>
			<v>1.558E-2</v>
			<v>1.526E-2</v>
			<v>2.214E-2</v>
			<v>2.886E-2</v>
			<v>1.915E-2</v>
			<v>1.221E-2</v>
			<v>1.303E-2</v>
			<v>1.42E-2</v>
			<v>1.868E-2</v>
			<v>3.377E-2</v>
			<v>3.24E-2</v>
			<v>2.959E-2</v>
			<v>2.246E-2</v>
			<v>1.226E-2</v>
			<v>8.189E-3</v>
			<v>6.715E-3</v>
			<v>6.788E-3</v>
			<v>5.899E-3</v>
			<v>5.553E-3</v>
			<v>6.704E-3</v>
			<v>8.259E-3</v>
			<v>6.012E-3</v>
			<v>4.941E-3</v>
			<v>4.971E-3</v>
			<v>6.334E-3</v>
			<v>4.639E-3</v>
			<v>3.763E-3</v>
			<v>3.077E-3</v>
			<v>2.3E-3</v>
			<v>2.758E-3</v>
			<v>4.148E-3</v>
			<v>4.833E-3</v>
			<v>3.972E-3</v>
			<v>3.964E-3</v>
			<v>4.422E-3</v>
			<v>6.752E-3</v>
			<v>6.897E-3</v>
			<v>4.659E-3</v>
			<v>3.148E-3</v>
			<v>2.198E-3</v>
			<v>2.511E-3</v>
			<v>3.535E-3</v>
			<v>6.259E-3</v>
			<v>8.025E-3</v>
			<v>6.234E-3</v>
			<v>6.189E-3</v>
			<v>3.739E-3</v>
			<v>2.235E-3</v>
			<v>2.556E-3</v>
			<v>3.231E-3</v>
			<v>3.377E-3</v>
			<v>2.599E-3</v>
			<v>2.419E-3</v>
			<v>1.813E-3</v>
			<v>2.14E-3</v>
			<v>2.645E-3</v>
			<v>3.331E-3</v>
			<v>2.627E-3</v>
			<v>3.235E-3</v>
			<v>3.042E-3</v>
			<v>1.765E-3</v>
			<v>1.765E-3</v>
			<v>2.382E-3</v>
			<v>3.551E-3</v>
			<v>2.254E-3</v>
			<v>4.308E-3</v>
			<v>7.978E-3</v>
			<v>5.597E-3</v>
			<v>4.13E-3</v>
			<v>2.838E-3</v>
			<v>2.474E-3</v>
			<v>3.262E-3</v>
			<v>3.202E-3</v>
			<v>2.925E-3</v>
			<v>3.501E-3</v>
			<v>4.477E-3</v>
			<v>4.788E-3</v>
			<v>6.192E-3</v>
			<v>7.364E-3</v>
			<v>5.003E-3</v>
			<v>3.27E-3</v>
			<v>3.038E-3</v>
			<v>2.353E-3</v>
			<v>1.764E-3</v>
			<v>1.586E-3</v>
			<v>1.73E-3</v>
			<v>1.812E-3</v>
			<v>1.858E-3</v>
			<v>2.118E-3</v>
			<v>1.946E-3</v>
			<v>2.16E-3</v>
			<v>2.439E-3</v>
			<v>2.171E-3</v>
			<v>1.928E-3</v>
			<v>2.373E-3</v>
			<v>2.814E-3</v>
			<v>3.241E-3</v>
			<v>3.046E-3</v>
			<v>2.21E-3</v>
			<v>2.254E-3</v>
			<v>2.401E-3</v>
			<v>2.761E-3</v>
			<v>1.96E-3</v>
			<v>1.572E-3</v>
			<v>1.62E-3</v>
			<v>1.535E-3</v>
			<v>2.136E-3</v>
			<v>2.004E-3</v>
			<v>2.342E-3</v>
			<v>2.395E-3</v>
			<v>2.124E-3</v>
			<v>1.874E-3</v>
			<v>1.804E-3</v>
			<v>2.127E-3</v>
			<v>2.393E-3</v>
			<v>1.937E-3</v>
			<v>1.585E-3</v>
			<v>1.996E-3</v>
			<v>2.175E-3</v>
			<v>2.591E-3</v>
			<v>2.478E-3</v>
			<v>2.237E-3</v>
			<v>3.662E-3</v>
			<v>3.663E-3</v>
			<v>2.594E-3</v>
			<v>2.708E-3</v>
			<v>2.213E-3</v>
			<v>2.275E-3</v>
			<v>2.104E-3</v>
			<v>2.147E-3</v>
			<v>1.872E-3</v>
			<v>1.826E-3</v>
			<v>2.401E-3</v>
			<v>3.205E-3</v>
			<v>2.961E-3</v>
			<v>2.668E-3</v>
			<v>2.611E-3</v>
			<v>2.233E-3</v>
			<v>2.508E-3</v>
		</feature>
		<feature>
			<name>FFT Bin Frequency Labels Overall Standard Deviation</name>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
		</feature>
		<feature>
			<name>Spectral Centroid Overall Standard Deviation</name>
			<v>1.229E1</v>
		</feature>
		<feature>
			<name>Spectral Rolloff Point Overall Standard Deviation</name>
			<v>1.112E-1</v>
		</feature>
		<feature>
			<name>Spectral Flux Overall Standard Deviation</name>
			<v>7.806E-3</v>
		</feature>
		<feature>
			<name>Compactness Overall Standard Deviation</name>
			<v>2.103E2</v>
		</feature>
		<feature>
			<name>Spectral Variability Overall Standard Deviation</name>
			<v>3.561E-3</v>
		</feature>
		<feature>
			<name>Root Mean Square Overall Standard Deviation</name>
			<v>1.386E-1</v>
		</feature>
		<feature>
			<name>Fraction Of Low Energy Windows Overall Standard Deviation</name>
			<v>6.861E-2</v>
		</feature>
		<feature>
			<name>Zero Crossings Overall Standard Deviation</name>
			<v>2.731E1</v>
		</feature>
		<feature>
			<name>Beat Histogram Overall Standard Deviation</name>
			<v>1.424E1</v>
			<v>1.421E1</v>
			<v>1.413E1</v>
			<v>1.405E1</v>
			<v>1.403E1</v>
			<v>1.398E1</v>
			<v>1.389E1</v>
			<v>1.382E1</v>
			<v>1.379E1</v>
			<v>1.374E1</v>
			<v>1.365E1</v>
			<v>1.357E1</v>
			<v>1.354E1</v>
			<v>1.348E1</v>
			<v>1.337E1</v>
			<v>1.329E1</v>
			<v>1.327E1</v>
			<v>1.322E1</v>
			<v>1.313E1</v>
			<v>1.306E1</v>
			<v>1.304E1</v>
			<v>1.297E1</v>
			<v>1.287E1</v>
			<v>1.279E1</v>
			<v>1.276E1</v>
			<v>1.27E1</v>
			<v>1.262E1</v>
			<v>1.255E1</v>
			<v>1.251E1</v>
			<v>1.245E1</v>
			<v>1.236E1</v>
			<v>1.229E1</v>
			<v>1.227E1</v>
			<v>1.222E1</v>
			<v>1.213E1</v>
			<v>1.207E1</v>
			<v>1.205E1</v>
			<v>1.199E1</v>
			<v>1.191E1</v>
			<v>1.184E1</v>
			<v>1.183E1</v>
			<v>1.178E1</v>
			<v>1.169E1</v>
			<v>1.164E1</v>
			<v>1.161E1</v>
			<v>1.154E1</v>
			<v>1.144E1</v>
			<v>1.137E1</v>
			<v>1.135E1</v>
			<v>1.128E1</v>
			<v>1.121E1</v>
			<v>1.118E1</v>
			<v>1.115E1</v>
			<v>1.109E1</v>
			<v>1.099E1</v>
			<v>1.093E1</v>
			<v>1.088E1</v>
			<v>1.081E1</v>
			<v>1.072E1</v>
			<v>1.069E1</v>
			<v>1.065E1</v>
			<v>1.058E1</v>
			<v>1.049E1</v>
			<v>1.044E1</v>
			<v>1.04E1</v>
			<v>1.033E1</v>
			<v>1.025E1</v>
			<v>1.021E1</v>
			<v>1.017E1</v>
			<v>1.011E1</v>
			<v>1.003E1</v>
			<v>9.985E0</v>
			<v>9.945E0</v>
			<v>9.881E0</v>
			<v>9.802E0</v>
			<v>9.763E0</v>
			<v>9.726E0</v>
			<v>9.655E0</v>
			<v>9.562E0</v>
			<v>9.512E0</v>
			<v>9.471E0</v>
			<v>9.396E0</v>
			<v>9.315E0</v>
			<v>9.28E0</v>
			<v>9.237E0</v>
			<v>9.168E0</v>
			<v>9.088E0</v>
			<v>9.047E0</v>
			<v>8.992E0</v>
			<v>8.914E0</v>
			<v>8.844E0</v>
			<v>8.808E0</v>
			<v>8.763E0</v>
			<v>8.685E0</v>
			<v>8.603E0</v>
			<v>8.563E0</v>
			<v>8.511E0</v>
			<v>8.437E0</v>
			<v>8.372E0</v>
			<v>8.339E0</v>
			<v>8.284E0</v>
			<v>8.211E0</v>
			<v>8.145E0</v>
			<v>8.104E0</v>
			<v>8.04E0</v>
			<v>7.964E0</v>
			<v>7.897E0</v>
			<v>7.861E0</v>
			<v>7.808E0</v>
			<v>7.729E0</v>
			<v>7.656E0</v>
			<v>7.609E0</v>
			<v>7.546E0</v>
			<v>7.467E0</v>
			<v>7.4E0</v>
			<v>7.37E0</v>
			<v>7.317E0</v>
			<v>7.248E0</v>
			<v>7.184E0</v>
			<v>7.145E0</v>
			<v>7.084E0</v>
			<v>6.998E0</v>
			<v>6.926E0</v>
			<v>6.886E0</v>
			<v>6.837E0</v>
			<v>6.762E0</v>
			<v>6.692E0</v>
			<v>6.65E0</v>
			<v>6.589E0</v>
			<v>6.507E0</v>
			<v>6.444E0</v>
			<v>6.405E0</v>
			<v>6.354E0</v>
			<v>6.284E0</v>
			<v>6.224E0</v>
			<v>6.188E0</v>
			<v>6.126E0</v>
			<v>6.045E0</v>
			<v>5.984E0</v>
			<v>5.944E0</v>
			<v>5.892E0</v>
			<v>5.819E0</v>
			<v>5.761E0</v>
			<v>5.718E0</v>
			<v>5.652E0</v>
			<v>5.572E0</v>
			<v>5.514E0</v>
			<v>5.473E0</v>
			<v>5.415E0</v>
			<v>5.346E0</v>
			<v>5.289E0</v>
			<v>5.239E0</v>
			<v>5.177E0</v>
			<v>5.102E0</v>
			<v>5.043E0</v>
			<v>4.993E0</v>
			<v>4.937E0</v>
			<v>4.87E0</v>
			<v>4.812E0</v>
			<v>4.761E0</v>
			<v>4.697E0</v>
			<v>4.623E0</v>
			<v>4.569E0</v>
			<v>4.525E0</v>
			<v>4.467E0</v>
			<v>4.399E0</v>
			<v>4.345E0</v>
			<v>4.3E0</v>
			<v>4.24E0</v>
			<v>4.165E0</v>
			<v>4.11E0</v>
		</feature>
		<feature>
			<name>Beat Histogram Bin Labels Overall Standard Deviation</name>
			<v>3.812E-11</v>
			<v>2.606E-11</v>
			<v>3.283E-11</v>
			<v>0E0</v>
			<v>9.238E-12</v>
			<v>2.638E-11</v>
			<v>2.925E-11</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>1.344E-11</v>
			<v>8.271E-12</v>
			<v>9.92E-12</v>
			<v>6.793E-12</v>
			<v>1.421E-14</v>
			<v>9.195E-12</v>
			<v>0E0</v>
			<v>9.095E-12</v>
			<v>1.906E-11</v>
			<v>1.067E-11</v>
			<v>1.303E-11</v>
			<v>7.788E-12</v>
			<v>1.641E-11</v>
			<v>1.823E-11</v>
			<v>0E0</v>
			<v>6.083E-12</v>
			<v>4.619E-12</v>
			<v>5.756E-12</v>
			<v>1.319E-11</v>
			<v>6.566E-12</v>
			<v>1.462E-11</v>
			<v>6.964E-12</v>
			<v>0E0</v>
			<v>3.965E-12</v>
			<v>0E0</v>
			<v>6.139E-12</v>
			<v>6.722E-12</v>
			<v>1.492E-12</v>
			<v>4.136E-12</v>
			<v>4.306E-12</v>
			<v>4.96E-12</v>
			<v>4.306E-12</v>
			<v>3.397E-12</v>
			<v>5.13E-12</v>
			<v>7.106E-15</v>
			<v>1.005E-11</v>
			<v>4.597E-12</v>
			<v>8.946E-12</v>
			<v>0E0</v>
			<v>3.766E-12</v>
			<v>4.548E-12</v>
			<v>3.24E-12</v>
			<v>9.529E-12</v>
			<v>5.898E-12</v>
			<v>5.336E-12</v>
			<v>8.69E-12</v>
			<v>6.516E-12</v>
			<v>6.85E-12</v>
			<v>3.894E-12</v>
			<v>0E0</v>
			<v>8.207E-12</v>
			<v>8.605E-12</v>
			<v>9.117E-12</v>
			<v>5.017E-12</v>
			<v>0E0</v>
			<v>3.446E-12</v>
			<v>3.041E-12</v>
			<v>4.761E-12</v>
			<v>2.309E-12</v>
			<v>8.449E-12</v>
			<v>2.878E-12</v>
			<v>3.823E-12</v>
			<v>6.594E-12</v>
			<v>6.964E-13</v>
			<v>3.283E-12</v>
			<v>6.722E-12</v>
			<v>7.312E-12</v>
			<v>5.237E-12</v>
			<v>3.482E-12</v>
			<v>4.171E-12</v>
			<v>0E0</v>
			<v>3.972E-12</v>
			<v>1.983E-12</v>
			<v>3.176E-12</v>
			<v>0E0</v>
			<v>5.543E-13</v>
			<v>3.07E-12</v>
			<v>8.378E-12</v>
			<v>3.361E-12</v>
			<v>2.565E-12</v>
			<v>7.461E-13</v>
			<v>1.727E-12</v>
			<v>2.068E-12</v>
			<v>4.441E-12</v>
			<v>2.153E-12</v>
			<v>2.778E-12</v>
			<v>2.48E-12</v>
			<v>4.676E-12</v>
			<v>2.153E-12</v>
			<v>6.523E-12</v>
			<v>1.698E-12</v>
			<v>2.196E-12</v>
			<v>2.565E-12</v>
			<v>4.022E-12</v>
			<v>3.553E-15</v>
			<v>2.48E-12</v>
			<v>5.024E-12</v>
			<v>4.899E-12</v>
			<v>2.299E-12</v>
			<v>0E0</v>
			<v>4.473E-12</v>
			<v>6.665E-12</v>
			<v>0E0</v>
			<v>1.46E-12</v>
			<v>1.883E-12</v>
			<v>2.672E-12</v>
			<v>2.274E-12</v>
			<v>2.409E-12</v>
			<v>1.62E-12</v>
			<v>2.764E-12</v>
			<v>4.764E-12</v>
			<v>1.684E-12</v>
			<v>2.949E-12</v>
			<v>1.919E-12</v>
			<v>2.668E-12</v>
			<v>3.372E-12</v>
			<v>4.345E-12</v>
			<v>1.656E-12</v>
			<v>3.258E-12</v>
			<v>3.471E-12</v>
			<v>3.425E-12</v>
			<v>3.674E-12</v>
			<v>1.947E-12</v>
			<v>2.896E-12</v>
			<v>0E0</v>
			<v>2.21E-12</v>
			<v>4.104E-12</v>
			<v>1.851E-12</v>
			<v>4.303E-12</v>
			<v>3.596E-12</v>
			<v>4.558E-12</v>
			<v>1.993E-12</v>
			<v>2.508E-12</v>
			<v>4.864E-12</v>
			<v>0E0</v>
			<v>3.08E-12</v>
			<v>1.723E-12</v>
			<v>2.213E-12</v>
			<v>1.521E-12</v>
			<v>9.806E-13</v>
			<v>2.38E-12</v>
			<v>4.782E-12</v>
			<v>1.155E-12</v>
			<v>3.098E-12</v>
			<v>4.224E-12</v>
			<v>9.06E-13</v>
			<v>1.439E-12</v>
			<v>2.501E-12</v>
			<v>1.911E-12</v>
			<v>8.527E-13</v>
			<v>3.297E-12</v>
			<v>1.506E-12</v>
			<v>3.482E-13</v>
			<v>1.279E-12</v>
			<v>1.641E-12</v>
			<v>3.091E-12</v>
			<v>3.361E-12</v>
			<v>5.685E-14</v>
			<v>3.656E-12</v>
			<v>1.983E-12</v>
			<v>2.618E-12</v>
			<v>1.375E-12</v>
		</feature>
		<feature>
			<name>Strongest Beat Overall Standard Deviation</name>
			<v>2.669E1</v>
		</feature>
		<feature>
			<name>Beat Sum Overall Standard Deviation</name>
			<v>1.559E3</v>
		</feature>
		<feature>
			<name>Strength Of Strongest Beat Overall Standard Deviation</name>
			<v>3.206E-4</v>
		</feature>
		<feature>
			<name>Strongest Frequency Via Zero Crossings Overall Standard Deviation</name>
			<v>4.268E2</v>
		</feature>
		<feature>
			<name>Strongest Frequency Via Spectral Centroid Overall Standard Deviation</name>
			<v>3.842E2</v>
		</feature>
		<feature>
			<name>Strongest Frequency Via FFT Maximum Overall Standard Deviation</name>
			<v>4.059E2</v>
		</feature>
		<feature>
			<name>MFCC Overall Standard Deviation</name>
			<v>1.881E1</v>
			<v>3.911E0</v>
			<v>3.668E0</v>
			<v>2.769E0</v>
			<v>2.356E0</v>
			<v>2.099E0</v>
			<v>2.36E0</v>
			<v>1.977E0</v>
			<v>2.196E0</v>
			<v>2.053E0</v>
			<v>1.986E0</v>
			<v>2.008E0</v>
			<v>2.059E0</v>
		</feature>
		<feature>
			<name>ConstantQ Overall Standard Deviation</name>
			<v>1.777E-1</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>1.299E-2</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
			<v>0E0</v>
		</feature>
		<feature>
			<name>LPC Overall Standard Deviation</name>
			<v>8.115E-2</v>
			<v>2.81E-1</v>
			<v>2.028E-1</v>
			<v>2.195E-1</v>
			<v>1.409E-1</v>
			<v>1.201E-1</v>
			<v>1.084E-1</v>
			<v>1.038E-1</v>
			<v>1.094E-1</v>
			<v>0E0</v>
		</feature>
		<feature>
			<name>Method of Moments Overall Standard Deviation</name>
			<v>4.175E-1</v>
			<v>1.452E1</v>
			<v>1.289E3</v>
			<v>1.063E5</v>
			<v>2.158E7</v>
		</feature>
		<feature>
			<name>Peak Detection Overall Standard Deviation</name>
			<v>4.046E-2</v>
			<v>3.14E-2</v>
			<v>1.878E-2</v>
			<v>1.718E-2</v>
			<v>1.685E-2</v>
			<v>1.546E-2</v>
			<v>1.536E-2</v>
			<v>1.395E-2</v>
			<v>1.27E-2</v>
			<v>1.11E-2</v>
			<v>9.23E-3</v>
			<v>7.925E-3</v>
			<v>7.285E-3</v>
			<v>7.068E-3</v>
			<v>6.323E-3</v>
			<v>5.858E-3</v>
			<v>5.302E-3</v>
			<v>5.567E-3</v>
			<v>4.863E-3</v>
		</feature>
		<feature>
			<name>Partial Based Spectral Centroid Overall Standard Deviation</name>
			<v>1.747E0</v>
		</feature>
		<feature>
			<name>Partial Based Spectral Flux Overall Standard Deviation</name>
			<v>NaN</v>
		</feature>
		<feature>
			<name>Peak Based Spectral Smoothness Overall Standard Deviation</name>
			<v>5.455E1</v>
		</feature>
		<feature>
			<name>Relative Difference Function Overall Standard Deviation</name>
			<v>1.369E0</v>
		</feature>
		<feature>
			<name>Area Method of Moments Overall Standard Deviation</name>
			<v>3.831E0</v>
			<v>1.213E4</v>
			<v>1.455E5</v>
			<v>1.759E11</v>
			<v>2.298E12</v>
			<v>2.984E13</v>
			<v>3.824E18</v>
			<v>2.071E13</v>
			<v>2.689E14</v>
			<v>9.181E21</v>
		</feature>
		<feature>
			<name>Area Method of Moments of MFCCs Overall Standard Deviation</name>
			<v>3.831E0</v>
			<v>1.213E4</v>
			<v>1.455E5</v>
			<v>1.759E11</v>
			<v>2.298E12</v>
			<v>2.984E13</v>
			<v>3.824E18</v>
			<v>2.071E13</v>
			<v>2.689E14</v>
			<v>9.181E21</v>
		</feature>
		<feature>
			<name>Area Method of Moments of Log of ConstantQ transform Overall Standard Deviation</name>
			<v>3.831E0</v>
			<v>1.213E4</v>
			<v>1.455E5</v>
			<v>1.759E11</v>
			<v>2.298E12</v>
			<v>2.984E13</v>
			<v>3.824E18</v>
			<v>2.071E13</v>
			<v>2.689E14</v>
			<v>9.181E21</v>
		</feature>
		<feature>
			<name>Area Method of Moments of ConstantQ-based MFCCs Overall Standard Deviation</name>
			<v>3.831E0</v>
			<v>1.213E4</v>
			<v>1.455E5</v>
			<v>1.759E11</v>
			<v>2.298E12</v>
			<v>2.984E13</v>
			<v>3.824E18</v>
			<v>2.071E13</v>
			<v>2.689E14</v>
			<v>9.181E21</v>
		</feature>
		<feature>
			<name>Magnitude Spectrum Overall Average</name>
			<v>3.364E-3</v>
			<v>1.844E-2</v>
			<v>3.941E-2</v>
			<v>3.468E-2</v>
			<v>2.403E-2</v>
			<v>2.94E-2</v>
			<v>3.305E-2</v>
			<v>1.96E-2</v>
			<v>1.94E-2</v>
			<v>1.638E-2</v>
			<v>1.316E-2</v>
			<v>1.848E-2</v>
			<v>1.682E-2</v>
			<v>1.189E-2</v>
			<v>1.228E-2</v>
			<v>1.257E-2</v>
			<v>1.13E-2</v>
			<v>1.611E-2</v>
			<v>1.049E-2</v>
			<v>7.464E-3</v>
			<v>7.401E-3</v>
			<v>7.067E-3</v>
			<v>9.585E-3</v>
			<v>1.09E-2</v>
			<v>6.007E-3</v>
			<v>7.951E-3</v>
			<v>9.106E-3</v>
			<v>5.552E-3</v>
			<v>8.461E-3</v>
			<v>9.343E-3</v>
			<v>6.622E-3</v>
			<v>5.511E-3</v>
			<v>5.629E-3</v>
			<v>8.05E-3</v>
			<v>1.316E-2</v>
			<v>9.025E-3</v>
			<v>3.121E-3</v>
			<v>2.953E-3</v>
			<v>4.722E-3</v>
			<v>4.704E-3</v>
			<v>4.479E-3</v>
			<v>3.858E-3</v>
			<v>3.647E-3</v>
			<v>4.221E-3</v>
			<v>3.208E-3</v>
			<v>4.304E-3</v>
			<v>4.605E-3</v>
			<v>2.951E-3</v>
			<v>2.436E-3</v>
			<v>2.349E-3</v>
			<v>3.263E-3</v>
			<v>5.017E-3</v>
			<v>4.137E-3</v>
			<v>3.018E-3</v>
			<v>3.025E-3</v>
			<v>2.577E-3</v>
			<v>3.598E-3</v>
			<v>5.059E-3</v>
			<v>4.275E-3</v>
			<v>3.04E-3</v>
			<v>3.635E-3</v>
			<v>3.357E-3</v>
			<v>2.529E-3</v>
			<v>2.653E-3</v>
			<v>2.911E-3</v>
			<v>3.083E-3</v>
			<v>2.669E-3</v>
			<v>3.212E-3</v>
			<v>5.324E-3</v>
			<v>5.307E-3</v>
			<v>3.119E-3</v>
			<v>2.734E-3</v>
			<v>2.626E-3</v>
			<v>2.223E-3</v>
			<v>2.321E-3</v>
			<v>2.609E-3</v>
			<v>3.556E-3</v>
			<v>4.239E-3</v>
			<v>2.979E-3</v>
			<v>2.77E-3</v>
			<v>3.633E-3</v>
			<v>3.084E-3</v>
			<v>2.267E-3</v>
			<v>1.968E-3</v>
			<v>2.194E-3</v>
			<v>3.568E-3</v>
			<v>4.308E-3</v>
			<v>3.28E-3</v>
			<v>2.509E-3</v>
			<v>2.396E-3</v>
			<v>2.952E-3</v>
			<v>3.863E-3</v>
			<v>3.587E-3</v>
			<v>2.506E-3</v>
			<v>2.22E-3</v>
			<v>2.127E-3</v>
			<v>2.273E-3</v>
			<v>2.158E-3</v>
			<v>1.872E-3</v>
			<v>1.908E-3</v>
			<v>2.096E-3</v>
			<v>2.233E-3</v>
			<v>3.691E-3</v>
			<v>4.063E-3</v>
			<v>2.393E-3</v>
			<v>1.956E-3</v>
			<v>2.315E-3</v>
			<v>2.542E-3</v>
			<v>2.187E-3</v>
			<v>1.666E-3</v>
			<v>1.53E-3</v>
			<v>1.792E-3</v>
			<v>2.092E-3</v>
			<v>2.316E-3</v>